version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: avito-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  parser:
    build: .
    container_name: avito-parser
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HEADLESS=true
      # Uncomment the line below to enable debug mode
      # - DEBUG=true
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  redis_data: